//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WP_Geocaching.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CacheTypeResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CacheTypeResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WP_Geocaching.Resources.Localization.CacheTypeResources", typeof(CacheTypeResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera.
        /// </summary>
        public static string camera {
            get {
                return ResourceManager.GetString("camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event.
        /// </summary>
        public static string cEvent {
            get {
                return ResourceManager.GetString("cEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkpoint.
        /// </summary>
        public static string checkpoint {
            get {
                return ResourceManager.GetString("checkpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Competition.
        /// </summary>
        public static string competition {
            get {
                return ResourceManager.GetString("competition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual.
        /// </summary>
        public static string cVirtual {
            get {
                return ResourceManager.GetString("cVirtual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extreme.
        /// </summary>
        public static string extreme {
            get {
                return ResourceManager.GetString("extreme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step by step traditional.
        /// </summary>
        public static string step_by_step_traditional {
            get {
                return ResourceManager.GetString("step_by_step_traditional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step by step virtual.
        /// </summary>
        public static string step_by_step_virtual {
            get {
                return ResourceManager.GetString("step_by_step_virtual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traditional.
        /// </summary>
        public static string traditional {
            get {
                return ResourceManager.GetString("traditional", resourceCulture);
            }
        }
    }
}
