//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeocachingPlus.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GeocachingComCacheType {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GeocachingComCacheType() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GeocachingPlus.Resources.Localization.GeocachingComCacheType", typeof(GeocachingComCacheType).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache In Trash Out.
        /// </summary>
        internal static string CITO {
            get {
                return ResourceManager.GetString("CITO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earth.
        /// </summary>
        internal static string EARTH {
            get {
                return ResourceManager.GetString("EARTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event.
        /// </summary>
        internal static string EVENT {
            get {
                return ResourceManager.GetString("EVENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groundspeak Headquarters.
        /// </summary>
        internal static string GCHQ {
            get {
                return ResourceManager.GetString("GCHQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exhibit.
        /// </summary>
        internal static string GPS_EXHIBIT {
            get {
                return ResourceManager.GetString("GPS_EXHIBIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letterbox.
        /// </summary>
        internal static string LETTERBOX {
            get {
                return ResourceManager.GetString("LETTERBOX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lost &amp; Found.
        /// </summary>
        internal static string LOSTANDFOUND {
            get {
                return ResourceManager.GetString("LOSTANDFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mega-Event.
        /// </summary>
        internal static string MEGA_EVENT {
            get {
                return ResourceManager.GetString("MEGA_EVENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi.
        /// </summary>
        internal static string MULTI {
            get {
                return ResourceManager.GetString("MULTI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puzzle.
        /// </summary>
        internal static string MYSTERY {
            get {
                return ResourceManager.GetString("MYSTERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project A.P.E..
        /// </summary>
        internal static string PROJECT_APE {
            get {
                return ResourceManager.GetString("PROJECT_APE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traditional.
        /// </summary>
        internal static string TRADITIONAL {
            get {
                return ResourceManager.GetString("TRADITIONAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string UNKNOWN {
            get {
                return ResourceManager.GetString("UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual.
        /// </summary>
        internal static string VIRTUAL {
            get {
                return ResourceManager.GetString("VIRTUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Webcam.
        /// </summary>
        internal static string WEBCAM {
            get {
                return ResourceManager.GetString("WEBCAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wherigo.
        /// </summary>
        internal static string WHERIGO {
            get {
                return ResourceManager.GetString("WHERIGO", resourceCulture);
            }
        }
    }
}
