//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WP_Geocaching.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WP_Geocaching.Resources.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AddCheckpointButton {
            get {
                return ResourceManager.GetString("AddCheckpointButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AddFavoritesButton {
            get {
                return ResourceManager.GetString("AddFavoritesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aerial.
        /// </summary>
        public static string AerialModeSettings {
            get {
                return ResourceManager.GetString("AerialModeSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        public static string ApplicationPivotTitle {
            get {
                return ResourceManager.GetString("ApplicationPivotTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GEOCACHING.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geocaching.
        /// </summary>
        public static string AppNameAbout {
            get {
                return ResourceManager.GetString("AppNameAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkpoint name.
        /// </summary>
        public static string CheckpointName {
            get {
                return ResourceManager.GetString("CheckpointName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to checkpoints.
        /// </summary>
        public static string CheckpointsButton {
            get {
                return ResourceManager.GetString("CheckpointsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose.
        /// </summary>
        public static string Choose {
            get {
                return ResourceManager.GetString("Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a cache.
        /// </summary>
        public static string ChooseCache {
            get {
                return ResourceManager.GetString("ChooseCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compass.
        /// </summary>
        public static string Compass {
            get {
                return ResourceManager.GetString("Compass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to compass.
        /// </summary>
        public static string CompassSearchButton {
            get {
                return ResourceManager.GetString("CompassSearchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {2} {0}° {1:F3}&apos; | {5} {3}° {4:F3}&apos;.
        /// </summary>
        public static string CoordinateFormat {
            get {
                return ResourceManager.GetString("CoordinateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd°,mm.mmm&apos;.
        /// </summary>
        public static string Coordinates {
            get {
                return ResourceManager.GetString("Coordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd,dddddd°.
        /// </summary>
        public static string DCoordinates {
            get {
                return ResourceManager.GetString("DCoordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkpoint {0}.
        /// </summary>
        public static string DefaultCheckpointName {
            get {
                return ResourceManager.GetString("DefaultCheckpointName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        public static string DeleteFavoritesButton {
            get {
                return ResourceManager.GetString("DeleteFavoritesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string DetailsTitle {
            get {
                return ResourceManager.GetString("DetailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E.
        /// </summary>
        public static string EastLongitude {
            get {
                return ResourceManager.GetString("EastLongitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Geocaching].
        /// </summary>
        public static string EmailSubject {
            get {
                return ResourceManager.GetString("EmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites.
        /// </summary>
        public static string Favorites {
            get {
                return ResourceManager.GetString("Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string InfoAbout {
            get {
                return ResourceManager.GetString("InfoAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to km.
        /// </summary>
        public static string Kilometres {
            get {
                return ResourceManager.GetString("Kilometres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude:.
        /// </summary>
        public static string Latitude {
            get {
                return ResourceManager.GetString("Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {2} {0}° {1:F3}&apos;.
        /// </summary>
        public static string LatitudeFormat {
            get {
                return ResourceManager.GetString("LatitudeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude:.
        /// </summary>
        public static string Longitude {
            get {
                return ResourceManager.GetString("Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {2} {0}° {1:F3}&apos;.
        /// </summary>
        public static string LongitudeFormat {
            get {
                return ResourceManager.GetString("LongitudeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map mode.
        /// </summary>
        public static string MapModeSettings {
            get {
                return ResourceManager.GetString("MapModeSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        public static string MapSettings {
            get {
                return ResourceManager.GetString("MapSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m.
        /// </summary>
        public static string Metres {
            get {
                return ResourceManager.GetString("Metres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to my location.
        /// </summary>
        public static string MyLocationButton {
            get {
                return ResourceManager.GetString("MyLocationButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to next.
        /// </summary>
        public static string NextButton {
            get {
                return ResourceManager.GetString("NextButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You haven&apos;t chosen any favorite caches yet.
        /// </summary>
        public static string NoFavoriteCachesMessage {
            get {
                return ResourceManager.GetString("NoFavoriteCachesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N.
        /// </summary>
        public static string NorthLatitude {
            get {
                return ResourceManager.GetString("NorthLatitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose a cache to search first.
        /// </summary>
        public static string NoSouhgtCacheMessage {
            get {
                return ResourceManager.GetString("NoSouhgtCacheMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to notebook.
        /// </summary>
        public static string NotebookButton {
            get {
                return ResourceManager.GetString("NotebookButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notebook.
        /// </summary>
        public static string NotebookTitle {
            get {
                return ResourceManager.GetString("NotebookTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photos.
        /// </summary>
        public static string PhotosTitle {
            get {
                return ResourceManager.GetString("PhotosTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to previous.
        /// </summary>
        public static string PreviousButton {
            get {
                return ResourceManager.GetString("PreviousButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Road.
        /// </summary>
        public static string RoadModeSettings {
            get {
                return ResourceManager.GetString("RoadModeSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        public static string SaveCheckpointButton {
            get {
                return ResourceManager.GetString("SaveCheckpointButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd°,mm&apos;ss.sss&apos;&apos;.
        /// </summary>
        public static string SCoordinates {
            get {
                return ResourceManager.GetString("SCoordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search.
        /// </summary>
        public static string SearchButton {
            get {
                return ResourceManager.GetString("SearchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search a cache.
        /// </summary>
        public static string SearchCache {
            get {
                return ResourceManager.GetString("SearchCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show all.
        /// </summary>
        public static string ShowAllButton {
            get {
                return ResourceManager.GetString("ShowAllButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.
        /// </summary>
        public static string SouthLatitude {
            get {
                return ResourceManager.GetString("SouthLatitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtype:.
        /// </summary>
        public static string Subtype {
            get {
                return ResourceManager.GetString("Subtype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string SupportAbout {
            get {
                return ResourceManager.GetString("SupportAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wp-geocaching-support@googlegroups.com.
        /// </summary>
        public static string SupportEmail {
            get {
                return ResourceManager.GetString("SupportEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many caches on the screen. Zoom in.
        /// </summary>
        public static string SurpassedCacheCountMessage {
            get {
                return ResourceManager.GetString("SurpassedCacheCountMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location is undetected.
        /// </summary>
        public static string UndetectedLocationMessage {
            get {
                return ResourceManager.GetString("UndetectedLocationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version 1.0.
        /// </summary>
        public static string VersionAbout {
            get {
                return ResourceManager.GetString("VersionAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W.
        /// </summary>
        public static string WestLongitude {
            get {
                return ResourceManager.GetString("WestLongitude", resourceCulture);
            }
        }
    }
}
