//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WP_Geocaching.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WP_Geocaching.Resources.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AddCheckpointButton {
            get {
                return ResourceManager.GetString("AddCheckpointButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AddFavoritesButton {
            get {
                return ResourceManager.GetString("AddFavoritesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GEOCACHING.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkpoint name.
        /// </summary>
        public static string CheckpointName {
            get {
                return ResourceManager.GetString("CheckpointName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to checkpoints.
        /// </summary>
        public static string CheckpointsButton {
            get {
                return ResourceManager.GetString("CheckpointsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose.
        /// </summary>
        public static string Choose {
            get {
                return ResourceManager.GetString("Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a cache.
        /// </summary>
        public static string ChooseCache {
            get {
                return ResourceManager.GetString("ChooseCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compass.
        /// </summary>
        public static string Compass {
            get {
                return ResourceManager.GetString("Compass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd°,mm.mmm&apos;.
        /// </summary>
        public static string Coordinates {
            get {
                return ResourceManager.GetString("Coordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd,dddddd°.
        /// </summary>
        public static string DCoordinates {
            get {
                return ResourceManager.GetString("DCoordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkpoint {0}.
        /// </summary>
        public static string DefaultCheckpointName {
            get {
                return ResourceManager.GetString("DefaultCheckpointName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        public static string DeleteFavoritesButton {
            get {
                return ResourceManager.GetString("DeleteFavoritesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites.
        /// </summary>
        public static string Favorites {
            get {
                return ResourceManager.GetString("Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to km.
        /// </summary>
        public static string Kilometres {
            get {
                return ResourceManager.GetString("Kilometres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude:.
        /// </summary>
        public static string Latitude {
            get {
                return ResourceManager.GetString("Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude:.
        /// </summary>
        public static string Longitude {
            get {
                return ResourceManager.GetString("Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m.
        /// </summary>
        public static string Metres {
            get {
                return ResourceManager.GetString("Metres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before searching choose a cache, please.
        /// </summary>
        public static string NoSouhgtCacheMessage {
            get {
                return ResourceManager.GetString("NoSouhgtCacheMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is too much caches on the screen! Zoom in.
        /// </summary>
        public static string OverflowMessage {
            get {
                return ResourceManager.GetString("OverflowMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        public static string SaveCheckpointButton {
            get {
                return ResourceManager.GetString("SaveCheckpointButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd°,mm&apos;ss.sss&apos;&apos;.
        /// </summary>
        public static string SCoordinates {
            get {
                return ResourceManager.GetString("SCoordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search.
        /// </summary>
        public static string SearchButton {
            get {
                return ResourceManager.GetString("SearchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search a cache.
        /// </summary>
        public static string SearchCache {
            get {
                return ResourceManager.GetString("SearchCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show all.
        /// </summary>
        public static string ShowAllButton {
            get {
                return ResourceManager.GetString("ShowAllButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtype:.
        /// </summary>
        public static string Subtype {
            get {
                return ResourceManager.GetString("Subtype", resourceCulture);
            }
        }
    }
}
